num1 = input("Enter the first number: ")
num2 = input("Enter the second number: ")

addition = float(num1) + float(num2)
print("Addition:", addition)
subtraction = float(num1) - float(num2) 
print("Subtraction:", subtraction)
multiplication = float(num1) * float(num2)
print("Multiplication:", multiplication)
division = float(num1) / float(num2)
print("Division:", division)